### ISSUE TITLE
Anpassen des Timestamps

### ISSUE THREAD

**Issue by tobiasfaust** [fhem/fhem-controls-actions#233]
Hi,
aktuell ist es ja so, das im controls file alle FhemModule denselben TImestamp vom Ausführungszeitpunkt der GIthub-Action bekommen. Ist es möglich das dieser Timestamp sich nach dem echten letzten Änderungszeitpunkt richtet?

**Comment by sidey79** [comment]
Hast Du im Checkout die Historie mit ausgecheckt? Wenn ja, sollten die Zeitstempel auch zur letzten Änderung passend ermittelt werden.

**Comment by tobiasfaust** [comment]
Naja, mein yml file sieht so aus:
<pre>
# This is a basic workflow to help you get started with Actions

name: FhemControlsFile

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: update controls files
        uses: fhem/fhem-controls-actions@v2.00b
        with:
          filename: controls_tobiasfaust.txt 

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "update controls file" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
</pre>

Und dann kommt so ein controls file heraus:
<pre>
UPD 2024-03-16_13:50:08 12109  FHEM/97_TrashCal.pm
UPD 2024-03-16_13:50:08 38006  FHEM/98_MediaList.pm
UPD 2024-03-16_13:50:08 83476  FHEM/98_Text2Speech.pm
</pre>

Und ich habe nur 98_Text2Speech.pm angepasst

**Comment by tobiasfaust** [comment]
jetzt hab ichs geschnallt...
geändert und funktioniert:
<pre>
- uses: actions/checkout@v2
        with:
          fetch-depth: 0
</pre>
