### ISSUE TITLE
Settings Option is missing in repository menu

### ISSUE THREAD

**Issue by sidey79** [fhem/fhem-controls-actions#9]
I currently have not the rights to configure this repository, what i need and i think i had them in the past.

![image](https://user-images.githubusercontent.com/7968127/103489875-fbc2e400-4e17-11eb-916b-efde7b782af1.png)

@jpawlowski @christoph-morrison @justme-1968  @LeonGaultier 
Can someone help me out here?

**Comment by christoph-morrison** [comment]
Please check again

**Comment by sidey79** [comment]
@christoph-morrison 

Thanks for that quick help, works now as it should :)

![image](https://user-images.githubusercontent.com/7968127/103490149-29a92800-4e1a-11eb-9fc3-49f81ca8b60e.png)

**Comment by christoph-morrison** [comment]
you are welcome
